name: Build and Publish JAR

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Build with Gradle (via Nix flake)
      run: |
        nix develop --command bash -c "
          chmod +x ./gradlew
          ./gradlew build --no-daemon
        "
      env:
        JAVA_OPTS: "-Dfile.encoding=UTF-8"
    
    - name: Publish to GitHub Packages
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
      run: |
        nix develop --command bash -c "
          ./gradlew publish --no-daemon
        "
      env:
        JAVA_OPTS: "-Dfile.encoding=UTF-8"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REPOSITORY: ${{ github.repository }}
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifact
        path: build/libs/*.jar
        retention-days: 30 