name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  packages: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build with Gradle (via Nix flake)
      run: |
        nix develop --command bash -c "
          chmod +x ./gradlew
          ./gradlew build --no-daemon
        "
      env:
        JAVA_OPTS: "-Dfile.encoding=UTF-8"

    - name: Create Release and Upload JAR
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: build/libs/*.jar
        generate_release_notes: true
        fail_on_unmatched_files: true